name: Bug Report
description: |
        Describe clearly and concisely a summary of the bug or defect.
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
    validations:
      required: true
